# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 23:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('done', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.Project')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.Person')),
            ],
        ),
        migrations.RemoveField(
            model_name='activity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='responsable',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
