# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0005_remove_perfil_bloqueados'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(null=True, upload_to='posts/'),
        ),
    ]
